<img src="TechLabs.png">

<h2>Please enter your full name here:</h2>


<p> This exam will test your knowledge in Data Science. </p>
<p> We will test the following: </p>
    
- Basic knowledge in Data Science
- How to manipulate data
- How to clean data
- Further data analysis

<h2>1. Basic Knowledge Test</h2>

A) Create a dictionary and a list.

In [7]:
dictionary = {1:'Italy', 2:'sea'}
print(directionary)
xlist = [2, 4, 6, 8, 10]
print(xlist)

{1: 'Italy', 2: 'sea'}
[2, 4, 6, 8, 10]


B) Create your own array containing multiple lists (at least 5 rows and 4 columns).

In [31]:
import numpy as np
array=np.array([[1,6,11,16],[2,7,12,17],[3,8,13,18],[4,9,14,19],[5,10,15,20]])
print(array)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


C) Convert your previous array into a pandas dataframe.

In [57]:
import pandas as pd
df=pd.DataFrame(data=array)
print(df)

   0   1   2   3
0  1   6  11  16
1  2   7  12  17
2  3   8  13  18
3  4   9  14  19
4  5  10  15  20


 D) Please write a function that will start with the number 2 and will add 3 as long as the number is under 25.

In [58]:
def calc_function():
    i = 2
    while i < 25:
        i = i + 3
        print(i)
calc_function()

5
8
11
14
17
20
23
26


E) Briefly explain what a lambda function is and its benefits over using regular functions.

F) What is the difference between relational and non-relational databases?

In [ ]:
# Difference: how data is stored

<h2>2. Manipulating Data </h2>

Dataset used: "AB_NYC_2019.csv" </p>
In this part of the exam you will have to play around with a dataset and display subsets of the data.

In [1]:
# Place all packages you need here


A) Load "AB_NYC_2019.csv",  drop all null values, and name it "df".

In [19]:
dfNY19=pd.read_csv("AB_NYC_2019.csv")
df=dfNY19.dropna()
print(df)

             id                                              name    host_id  \
0          2539                Clean & quiet apt home by the park       2787   
1          2595                             Skylit Midtown Castle       2845   
3          3831                   Cozy Entire Floor of Brownstone       4869   
4          5022  Entire Apt: Spacious Studio/Loft by central park       7192   
5          5099         Large Cozy 1 BR Apartment In Midtown East       7322   
...         ...                                               ...        ...   
48782  36425863        Lovely Privet Bedroom with Privet Restroom   83554966   
48790  36427429                          No.2 with queen size bed  257683179   
48799  36438336                                   Seas The Moment  211644523   
48805  36442252                     1B-1B apartment near by Metro  273841667   
48852  36455809           Cozy Private Room in Bushwick, Brooklyn   74162901   

         host_name neighbourhood_group 

B) Within the dataframe "df", permanently rename the column "name" to "listing_name".

In [23]:
df.rename(columns={'name':'listing_name'})

id                                      listing_name  \
0          2539                Clean & quiet apt home by the park   
1          2595                             Skylit Midtown Castle   
3          3831                   Cozy Entire Floor of Brownstone   
4          5022  Entire Apt: Spacious Studio/Loft by central park   
5          5099         Large Cozy 1 BR Apartment In Midtown East   
...         ...                                               ...   
48782  36425863        Lovely Privet Bedroom with Privet Restroom   
48790  36427429                          No.2 with queen size bed   
48799  36438336                                   Seas The Moment   
48805  36442252                     1B-1B apartment near by Metro   
48852  36455809           Cozy Private Room in Bushwick, Brooklyn   

         host_name neighbourhood_group    neighbourhood  latitude  longitude  \
0             John            Brooklyn       Kensington  40.64749  -73.97237   
1         Jennifer           Manhattan          Midtown  40.75362  -73.98377   
3      LisaRoxanne            Brooklyn     Clinton Hill  40.68514  -73.95976   
4            Laura           Manhattan      East Harlem  40.79851  -73.94399   
5            Chris           Manhattan      Murray Hill  40.74767  -73.97500   
...            ...                 ...              ...       ...        ...   
48782        Rusaa           Manhattan  Upper East Side  40.78099  -73.95366   
48790         H Ai              Queens         Flushing  40.75104  -73.81459   
48799          Ben       Staten Island      Great Kills  40.54179  -74.14275   
48805       Blaine               Bronx       Mott Haven  40.80787  -73.92400   
48852    Christine            Brooklyn         Bushwick  40.69805  -73.92801   

             room_type  price  minimum_nights  number_of_reviews last_review  \
0         Private room    149               1                  9  2018-10-19   
1      Entire home/apt    225               1                 45  2019-05-21   
3      Entire home/apt     89               1                270  2019-07-05   
4      Entire home/apt     80              10                  9  2018-11-19   
5      Entire home/apt    200               3                 74  2019-06-22   
...                ...    ...             ...                ...         ...   
48782     Private room    129               1                  1  2019-07-07   
48790     Private room     45               1                  1  2019-07-07   
48799     Private room    235               1                  1  2019-07-07   
48805  Entire home/apt    100               1                  2  2019-07-07   
48852     Private room     30               1                  1  2019-07-08   

       reviews_per_month  calculated_host_listings_count  availability_365  
0                   0.21                               6               365  
1                   0.38                               2               355  
3                   4.64                               1               194  
4                   0.10                               1                 0  
5                   0.59                               1               129  
...                  ...                             ...               ...  
48782               1.00                               1               147  
48790               1.00                               6               339  
48799               1.00                               1                87  
48805               2.00                               1                40  
48852               1.00                               1                 1  

[38821 rows x 15 columns]

C) Drop the column host_id. Save the new dataframe again under the name "df".

In [65]:
df = df.drop(['host_id'], axis = 1)

KeyError: 'host_id'

D) Only show listings with a price higher than the average price. Sort the dataframe by price in an ascending order.

In [62]:
df_sortprice = df.loc[df['price'] > df['price'].mean()]
df_sortprice.sort_values(by = ['price'], inplace = True)

KeyError: 'price'

E) Only show listings that have more than the average reviews and that are available for more than 10 nights (column "minimum_nights"). Sort the dataframe by reviews in a descending order.

In [ ]:
df_sortrev = df.loc[df['number_of_reviews'] > df['number_of_reviews'].mean()]
df_sortrev = df.loc[df['minimum_nights'] > 10]
df_sortrev.sort_values(by = ['number_of_reviews'], ascending = False, inplace = True)

F) Display the number of listings per neighbourhood and only display those neighbourhoods with more than 1000 listings.

In [ ]:
count = df['neighbourhood'].value_counts()
count[count > 1000]

G) Display the number of the different types of rooms (column "room_type") per neighbourhood.

In [ ]:
df['counting'] = 1
table_rooms = pd.pivot_table(df, index = df['neighbourhood'], columns = df['room_type'], aggfunc=np.sum)
table_rooms['counting']

H) Replace the values within "room_type" with numerical values, i.e. 0 for "private room", 1 for "Entire home/apt", and 2 for "Shared room". </p>
Save the new dataframe again under the name "df".

In [ ]:
df = df.replace(['Private room', 'Entire home/apt', 'Shared room'], ['0', '1', '2'])

I) Display a bar chart using the distplot (from the seaborn library) that shows the neighbourhood on the x-axis and the number of listings on the y-axis.

J) Scale the column "price" and the column "number_of_reviews" using a method that seems appropriate in your opinion. </p>
Save the new dataframe again under the name "df".

<h2>3. Cleaning Data</h2>

Dataset used: "defaults.xls"

In [3]:
# Place all packages you need here


A) Load the dataset "defaults.xls" and save it under the name "defaults". Display the datatypes of all columns of the dataset "defaults.xls".

In [66]:
defaults=pd.read_excel("defaults.xls")
print(defaults.dtypes)

ID               int64
CREDIT_LIMIT     int64
SEX             object
EDUCATION       object
MARRIAGE        object
AGE              int64
default          int64
dtype: object


B) Some column(s) might not be needed. Get rid of them. Explain why you get rid of the respective column(s). </p>
Save the new dataframe again under the name "defaults".

In [79]:
#default doesn't indicate anything and thus can be dropped
defaults=defaults.drop('default', inplace = True, axis = 1)

KeyError: "['default'] not found in axis"

C) Convert all categorical values into dummy variables. Only include columns with valuable information. </p>
Save the new dataframe again under the name "defaults".

In [67]:
defaults = pd.get_dummies(defaults[['SEX', 'EDUCATION', 'MARRIAGE']])
print(defaults)

       SEX_female  SEX_male  EDUCATION_graduate school  EDUCATION_high school  \
0               1         0                          0                      0   
1               1         0                          0                      0   
2               1         0                          0                      0   
3               1         0                          0                      0   
4               0         1                          0                      0   
...           ...       ...                        ...                    ...   
29596           0         1                          0                      1   
29597           0         1                          0                      1   
29598           0         1                          0                      0   
29599           0         1                          0                      1   
29600           0         1                          0                      0   

       EDUCATION_others  ED

D) In order to run a model, we have to define now the X and y variables. Set the y values to the "default" (either 0 or 1). The remaining columns represent the X values.

<h2>4. Further Data Analysis</h2>

A) Please evaluate the importance of each feature of the X values on the y value of the previous exercise using any tree ensamble algorithm and display the results graphically. Please comment your findings. Please tell us what you did and why you did it.

B) Please assess how accuarely we can predict, whether a customer will default or not using Support Vector Machines. As always plase explain your work.

C) Now let's see how accurate the XGBoost algorithm can predict, whether a customer will default or not better than the previous SVM. Please give us the accuracy score and standard deviation. Choose an appropiate model for testing and training.